micronaut:
  application:
    name: status_page
  server:
    host: localhost
    netty:
      worker:
        threads: 5
      parent:
        threads: 5
      childOptions:
        autoRead: true
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
