micronaut:
  application:
    name: status_page
  server:
    host: localhost
    cors:
      enabled: true
    netty:
      worker:
        threads: 5
      parent:
        threads: 5
      childOptions:
        autoRead: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"